apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chuck-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   
spec:
  project: chuck-project
  destination:
    namespace: chuck
    server: 'https://kubernetes.default.svc'
  source:
    path: ui
    repoURL: 'https://github.com/Dimss/chuck-forum19-demo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

